### ISSUE TITLE
Possible to cut a new gem

### ISSUE THREAD

**Issue by arronmabrey** [rubylit/guevara#4]
Hello,

Looking at the diffs here, there are some changes related to allowing ids with leading 0s. I'm currently referencing the latest master sha, but it would work much better if there was a new gem built. 

https://github.com/rubylit/guevara/compare/v0.2.0...master

Thanks

**Comment by eloyesp** [comment]
Hi, thanks for the reminder. I've just released the v1.0.

**Comment by arronmabrey** [comment]
Thanks!
